name: ${project.name}
main: com.projectg.geyserupdater.spigot.SpigotUpdater
version: ${project.version}
api-version: 1.13
description: Automatically or manually downloads new builds of Geyser and applies them on server restart.
authors:
  - Jens
  - Konicai

commands:
  geyserupdate:
    description: updating Geyser command
    permission: gupdater.geyserupdate
    aliases: /geyserupdate
